#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesWithSQL.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Movies")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertelokuvat(elokuvat instance);
    partial void Updateelokuvat(elokuvat instance);
    partial void Deleteelokuvat(elokuvat instance);
    partial void InsertJulkaisijat(Julkaisijat instance);
    partial void UpdateJulkaisijat(Julkaisijat instance);
    partial void DeleteJulkaisijat(Julkaisijat instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::MoviesWithSQL.Properties.Settings.Default.MoviesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<elokuvat> elokuvats
		{
			get
			{
				return this.GetTable<elokuvat>();
			}
		}
		
		public System.Data.Linq.Table<Julkaisijat> Julkaisijats
		{
			get
			{
				return this.GetTable<Julkaisijat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.elokuvat")]
	public partial class elokuvat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nimi;
		
		private System.Nullable<short> _Julkaisuvuosi;
		
		private System.Nullable<short> _Kesto;
		
		private System.Nullable<byte> _Arvio;
		
		private string _Julkaisija;
		
		private System.Nullable<int> _JulkaisijaID;
		
		private EntityRef<Julkaisijat> _Julkaisijat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNimiChanging(string value);
    partial void OnNimiChanged();
    partial void OnJulkaisuvuosiChanging(System.Nullable<short> value);
    partial void OnJulkaisuvuosiChanged();
    partial void OnKestoChanging(System.Nullable<short> value);
    partial void OnKestoChanged();
    partial void OnArvioChanging(System.Nullable<byte> value);
    partial void OnArvioChanged();
    partial void OnJulkaisijaChanging(string value);
    partial void OnJulkaisijaChanged();
    partial void OnJulkaisijaIDChanging(System.Nullable<int> value);
    partial void OnJulkaisijaIDChanged();
    #endregion
		
		public elokuvat()
		{
			this._Julkaisijat = default(EntityRef<Julkaisijat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nimi", DbType="NVarChar(116)")]
		public string Nimi
		{
			get
			{
				return this._Nimi;
			}
			set
			{
				if ((this._Nimi != value))
				{
					this.OnNimiChanging(value);
					this.SendPropertyChanging();
					this._Nimi = value;
					this.SendPropertyChanged("Nimi");
					this.OnNimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Julkaisuvuosi", DbType="SmallInt")]
		public System.Nullable<short> Julkaisuvuosi
		{
			get
			{
				return this._Julkaisuvuosi;
			}
			set
			{
				if ((this._Julkaisuvuosi != value))
				{
					this.OnJulkaisuvuosiChanging(value);
					this.SendPropertyChanging();
					this._Julkaisuvuosi = value;
					this.SendPropertyChanged("Julkaisuvuosi");
					this.OnJulkaisuvuosiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kesto", DbType="SmallInt")]
		public System.Nullable<short> Kesto
		{
			get
			{
				return this._Kesto;
			}
			set
			{
				if ((this._Kesto != value))
				{
					this.OnKestoChanging(value);
					this.SendPropertyChanging();
					this._Kesto = value;
					this.SendPropertyChanged("Kesto");
					this.OnKestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arvio", DbType="TinyInt")]
		public System.Nullable<byte> Arvio
		{
			get
			{
				return this._Arvio;
			}
			set
			{
				if ((this._Arvio != value))
				{
					this.OnArvioChanging(value);
					this.SendPropertyChanging();
					this._Arvio = value;
					this.SendPropertyChanged("Arvio");
					this.OnArvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Julkaisija", DbType="NVarChar(MAX)")]
		public string Julkaisija
		{
			get
			{
				return this._Julkaisija;
			}
			set
			{
				if ((this._Julkaisija != value))
				{
					this.OnJulkaisijaChanging(value);
					this.SendPropertyChanging();
					this._Julkaisija = value;
					this.SendPropertyChanged("Julkaisija");
					this.OnJulkaisijaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JulkaisijaID", DbType="Int")]
		public System.Nullable<int> JulkaisijaID
		{
			get
			{
				return this._JulkaisijaID;
			}
			set
			{
				if ((this._JulkaisijaID != value))
				{
					if (this._Julkaisijat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnJulkaisijaIDChanging(value);
					this.SendPropertyChanging();
					this._JulkaisijaID = value;
					this.SendPropertyChanged("JulkaisijaID");
					this.OnJulkaisijaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Julkaisijat_elokuvat", Storage="_Julkaisijat", ThisKey="JulkaisijaID", OtherKey="Id", IsForeignKey=true)]
		public Julkaisijat Julkaisijat
		{
			get
			{
				return this._Julkaisijat.Entity;
			}
			set
			{
				Julkaisijat previousValue = this._Julkaisijat.Entity;
				if (((previousValue != value) 
							|| (this._Julkaisijat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Julkaisijat.Entity = null;
						previousValue.elokuvats.Remove(this);
					}
					this._Julkaisijat.Entity = value;
					if ((value != null))
					{
						value.elokuvats.Add(this);
						this._JulkaisijaID = value.Id;
					}
					else
					{
						this._JulkaisijaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Julkaisijat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public static implicit operator elokuvat(DataClasses1DataContext v)
		{
			throw new NotImplementedException();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Julkaisijat")]
	public partial class Julkaisijat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Julkaisija;
		
		private EntitySet<elokuvat> _elokuvats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnJulkaisijaChanging(string value);
    partial void OnJulkaisijaChanged();
    #endregion
		
		public Julkaisijat()
		{
			this._elokuvats = new EntitySet<elokuvat>(new Action<elokuvat>(this.attach_elokuvats), new Action<elokuvat>(this.detach_elokuvats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Julkaisija", DbType="NVarChar(MAX)")]
		public string Julkaisija
		{
			get
			{
				return this._Julkaisija;
			}
			set
			{
				if ((this._Julkaisija != value))
				{
					this.OnJulkaisijaChanging(value);
					this.SendPropertyChanging();
					this._Julkaisija = value;
					this.SendPropertyChanged("Julkaisija");
					this.OnJulkaisijaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Julkaisijat_elokuvat", Storage="_elokuvats", ThisKey="Id", OtherKey="JulkaisijaID")]
		public EntitySet<elokuvat> elokuvats
		{
			get
			{
				return this._elokuvats;
			}
			set
			{
				this._elokuvats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_elokuvats(elokuvat entity)
		{
			this.SendPropertyChanging();
			entity.Julkaisijat = this;
		}
		
		private void detach_elokuvats(elokuvat entity)
		{
			this.SendPropertyChanging();
			entity.Julkaisijat = null;
		}
	}
}
#pragma warning restore 1591
